name: dem-handler
channels:
  - conda-forge
dependencies:
  - rasterio=1.4.3
  - gdal=3.10.2
  - pip:
    - boto3==1.37.6
    - geopandas==1.0.1
    - ipykernel
    - pytest==8.3.5
    - requests==2.32.3