name: Run Tests with Pixi

on:
  pull_request:

jobs:
  run-tests:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - name: Run tests
    uses: prefix-dev/setup-pixi@v0.8.3
    with:
      pixi-version: v0.42.1
      cache: true
      auth-host: prefix.dev
      auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
    run: pixi run test