name: Run Tests with Pytest

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - uses: actions/cache@v4
      with:
        path: |
          tests/cop_glo30/data/**
          tests/rema/data/**
          tests/data/geoid/**
        key: ${{ runner.os }}-${{ hashFiles('tests/**/*.tif') }}
    - name: Set up micromamba environment
      uses: mamba-org/setup-micromamba@v2.0.3
      with:
        generate-run-shell: true
        environment-file: environment.yaml
    - name: Check packages
      shell: micromamba-shell {0}
      run: |
        pytest --version
    - name: Install dem-handler package
      shell: micromamba-shell {0}
      run: |
        pip install .
    - name: Run tests
      shell: micromamba-shell {0}
      run: |
        coverage run -m pytest tests/
        coverage xml
    - name: Lint
      uses: psf/black@stable
      with:
        options: "--check --verbose"
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml